"""add org owner_user_id

Revision ID: 9a92254988d3
Revises: ae1ac4b075ee
Create Date: 2026-04-22 11:13:02.675681

"""

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = '9a92254988d3'
down_revision = 'ae1ac4b075ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()

    # 1) Add nullable column first (safe for existing rows)
    op.add_column('organizations', sa.Column('owner_user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)

    # 2) Backfill from memberships: pick active owner; fallback to earliest active membership.
    orgs = [row[0] for row in bind.execute(sa.text("SELECT id FROM organizations")).fetchall()]
    for org_id in orgs:
        owner = bind.execute(
            sa.text(
                """
                SELECT user_id FROM memberships
                WHERE organization_id = :org_id
                  AND status = 'active'
                  AND role = 'owner'
                ORDER BY created_at ASC
                LIMIT 1
                """
            ),
            {"org_id": org_id},
        ).fetchone()
        if owner is None:
            owner = bind.execute(
                sa.text(
                    """
                    SELECT user_id FROM memberships
                    WHERE organization_id = :org_id
                      AND status = 'active'
                    ORDER BY created_at ASC
                    LIMIT 1
                    """
                ),
                {"org_id": org_id},
            ).fetchone()
        if owner is not None and owner[0]:
            bind.execute(
                sa.text("UPDATE organizations SET owner_user_id = :uid WHERE id = :org_id"),
                {"uid": owner[0], "org_id": org_id},
            )

    # 3) Enforce NOT NULL only if backfill succeeded everywhere (keeps migration safe).
    nulls = bind.execute(sa.text("SELECT COUNT(*) FROM organizations WHERE owner_user_id IS NULL")).fetchone()
    if nulls and int(nulls[0] or 0) == 0:
        with op.batch_alter_table("organizations") as batch_op:
            batch_op.alter_column("owner_user_id", existing_type=sa.String(length=36), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_column('organizations', 'owner_user_id')
    # ### end Alembic commands ###

